version: '3' # версия синтаксиса
services:
 express-app: # Сервер Express
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DATABASE_URL: 'mongodb://monty:pass@db:27017/mydatabase?authSource=admin&directConnection=true'
 db: # База данных
    image: prismagraphql/mongo-single-replica:5.0.3
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: monty
      MONGO_INITDB_ROOT_PASSWORD: pass
 react-app: # React-приложение
    build: ../tech-forum # Путь к React-приложению относительно корня вашего проекта
    ports:
      - '80:80' # Порт, на котором будет доступно React-приложение
      - '8000:8000' # Порт, на котором будет доступно React-приложение
volumes:
 react_app: # Объявление именованного тома